apiVersion: v2
name: centralized
description: Helm for installing Centralized
type: application
version: 0.2.1
appVersion: "0.3.21"
dependencies:
  - name: postgresql
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql
