kind: template
load: build-docker.drone.yml

trigger:
  event:
    - push
    - custom
  branch:
    - main

data:
  arch: amd64

---
kind: pipeline
load: build-docker.yml

trigger:
  event:
    - push
    - custom
  branch:
    - main

data:
  arch: arm64

---
kind: pipeline
type: docker
name: manifest

trigger:
  event:
    - push
    - custom
  branch:
    - main

platform:
  os: linux
  arch: arm64

steps:
  - name: manifest
    image: docker:24.0.5
    depends_on:
      - build-amd64
      - build-arm64
    commands:
      - docker login ghcr.io -u "${GITHUB_USERNAME}" -p "${GITHUB_TOKEN}"
      - docker manifest create ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH} \
          ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:amd64 \
          ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:arm64
      - docker manifest annotate ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH} \
          ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:amd64 --os linux --arch amd64
      - docker manifest annotate ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH} \
          ghcr.io/${DRONE_REpo_OWNER}/${DRONE_REPO_NAME}:arm64 --os linux --arch arm64
      - docker manifest push ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH}
