kind: pipeline
type: docker
name: build-amd64

trigger:
  event:
    - push
    - custom
  branch:
    - main

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      tags:
        - amd64
      dockerfile: ./docker/prod/Dockerfile
      context: .
      build_args:
        - "BUILDKIT_INLINE_CACHE=1"
      buildx: false
      registry: ghcr.io
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN

---
kind: pipeline
type: docker
name: build-arm64

trigger:
  event:
    - push
    - custom
  branch:
    - main

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      tags:
        - arm64
      dockerfile: ./docker/prod/Dockerfile
      context: .
      build_args:
        - "BUILDKIT_INLINE_CACHE=1"
      buildx: false
      registry: ghcr.io
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN

---
kind: pipeline
type: docker
name: manifest

trigger:
  event:
    - push
    - custom
  branch:
    - main

platform:
  os: linux
  arch: arm64

depends_on:
  - build-amd64
  - build-arm64

steps:
  - name: manifest
    image: docker:24.0.5
    environment:
      GITHUB_USERNAME:
        from_secret: GITHUB_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_USERNAME
    commands:
      - docker login ghcr.io -u "${GITHUB_USERNAME}" -p "${GITHUB_TOKEN}"
      - docker manifest create ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH} \
          ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:amd64 \
          ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:arm64
      - docker manifest annotate ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH} \
          ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:amd64 --os linux --arch amd64
      - docker manifest annotate ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH} \
          ghcr.io/${DRONE_REpo_OWNER}/${DRONE_REPO_NAME}:arm64 --os linux --arch arm64
      - docker manifest push ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_REPO_BRANCH}
