

kind: pipeline
type: docker
name: tag-release

trigger:
  event:
    - push

platform:
  os: linux
  arch: arm64

steps:
  - name: image-tag-release
    image: docker:24.0.5
    environment:
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - |
        docker buildx imagetools create \
          --tag ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:0.1.1 \
          ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:latest
  
  - name: update-chart-version
    image: alpine/git:latest
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
    commands:
      - apk add --no-cache yq
      - git config --global user.email "drone@ci.rigidd.app"
      - git config --global user.name "Drone Rigidd"
      - git config --global credential.helper store
      - echo "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" > ~/.git-credentials
      - |
        CHART_PATH="Chart.yaml"
        VERSION=0.1.1
        echo "Updating Chart.yaml with version: $VERSION"
        yq eval '.appVersion = "'$VERSION'"' -i $CHART_PATH
        git add $CHART_PATH
        git commit -m "chore: bump chart version to $VERSION [CI SKIP]" || echo "No changes to commit"
        git push origin HEAD:main
      - git clone https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/${DRONE_REPO_OWNER}/helm-charts.git /tmp/helm-charts

  - name: push-chart
    image: alpine/git:latest
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
    commands:
      - apk add --no-cache helm
      - git config --global user.email "drone@ci.rigidd.app"
      - git config --global user.name "Drone Rigidd"
      - git config --global credential.helper store
      - echo "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" > ~/.git-credentials
      - |
        VERSION=${DRONE_TAG#v}
        helm dependency update
        helm package . --destination /tmp/helm-charts
        cd /tmp/helm-charts
        helm repo index . --url https://${DRONE_REPO_OWNER}.github.io/helm-charts
        git add .
        git commit -m "chore: publish ${DRONE_REPO_NAME} chart version $VERSION" || echo "No changes to commit"
        git push origin main

