kind: pipeline
type: docker
name: build-${{ .input.arch }}

platform:
  os: linux
  arch: ${{ .input.arch }}

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ghcr.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      tags:
        - ${{ .input.arch }}
      dockerfile: ./docker/prod/Dockerfile
      context: .
      build_args:
        - "BUILDKIT_INLINE_CACHE=1"
      buildx: false
      registry: ghcr.io
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
