apiVersion: v1
kind: Secret
metadata:
  name: {{ include "centralized.fullname" . }}-app-config
type: Opaque
stringData:
    APP_NAME: {{ .Values.app.name | default "Centralized" | quote }}
    APP_DEBUG: {{ .Values.app.debug | default false | quote }}
    APP_TIMEZONE: {{ .Values.app.timezone | default "UTC" | quote }}
    APP_URL: {{ .Values.app.url | quote }}

    AUTH_REQUIRE_MFA: {{ .Values.app.auth.requireMfa | default true | quote }}

    AUTH_REGISTRATION: {{ .Values.app.auth.registration | default false | quote }}

    APP_LOCALE: {{ .Values.app.locale.app | default "en" | quote }}
    APP_FALLBACK_LOCALE: {{ .Values.app.locale.fallback | default "en" | quote }}
    APP_FAKER_LOCALE: {{ .Values.app.locale.faker | default "en_US" | quote }}

    APP_MAINTENANCE_DRIVER: {{ .Values.app.maintenanceDriver | default "file" | quote }}

    PHP_CLI_SERVER_WORKERS: {{ .Values.app.phpCliServerWorkers | default 4 | quote }}

    BCRYPT_ROUNDS: {{ .Values.app.bcryptRounds | default 12 | quote }}

    LOG_CHANNEL: {{ .Values.app.log.channel | default "stack" | quote }}
    LOG_STACK: {{ .Values.app.log.stack | default "single" | quote }}
    LOG_DEPRECATIONS_CHANNEL: {{ .Values.app.log.deprecationsChannel | default "null" | quote }}
    LOG_LEVEL: {{ .Values.app.log.level | default "debug" | quote }}

    SESSION_DRIVER: {{ .Values.app.session.driver | default "database" | quote }}
    SESSION_LIFETIME: {{ .Values.app.session.lifetime | default "120" | quote }}
    SESSION_ENCRYPT: {{ .Values.app.session.encrypt | default "false" | quote }}
    SESSION_PATH: {{ .Values.app.session.path | default "/" | quote }}
    SESSION_DOMAIN: {{ .Values.app.session.domain | default "null" | quote }}
    BROADCAST_CONNECTION: log
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: database

    CACHE_STORE: {{ .Values.app.cache.store | default "database" | quote }}
    CACHE_PREFIX: {{ .Values.app.cache.prefix | default "" | quote }}

    MEMCACHED_HOST: {{ .Values.app.memcached.host | default "127.0.0.1" | quote }}

    REDIS_CLIENT: {{ .Values.app.redis.client | default "phpredis" | quote }}
    REDIS_HOST: {{ .Values.app.redis.host | default "127.0.0.1" | quote }}
    REDIS_PASSWORD: {{ .Values.app.redis.password | default "null" | quote }}
    REDIS_PORT: {{ .Values.app.redis.port | default "6379" | quote }}

    MAIL_MAILER: {{ .Values.app.mail.mailer | default "mailjet" | quote }}
    MAIL_FROM_ADDRESS: {{ .Values.app.mail.fromAddress | default "centralized@rigidd.app" | quote }}
    MAIL_FROM_NAME: {{ .Values.app.mail.fromName | default "Centralized - Rigidd" | quote }}
    MAILJET_APIKEY: {{ .Values.app.mail.mailjet.apiKey | default "" | quote }}
    MAILJET_APISECRET: {{ .Values.app.mail.mailjet.apiSecret | default "" | quote }}

    AWS_ACCESS_KEY_ID: {{ .Values.app.aws.accessKeyId | default "" | quote }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.app.aws.secretAccessKey | default "" | quote }}
    AWS_DEFAULT_REGION: {{ .Values.app.aws.defaultRegion | default "us-east-1" | quote }}
    AWS_BUCKET: {{ .Values.app.aws.bucket | default "" | quote }}
    AWS_USE_PATH_STYLE_ENDPOINT: {{ .Values.app.aws.usePathStyleEndpoint | default "false" | quote }}

    VITE_APP_NAME: "${APP_NAME}"

    OCTANE_SERVER: frankenphp